spring:
  datasource:
    url: jdbc:mysql://withyan.cn:3306/oppo?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Yan1996>
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    
